services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel
    volumes:
      - ./:/var/www
      - ./database:/var/www/database
    networks:
      - laravel
    restart: unless-stopped
    ports:
      - "9000:9000"

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - .:/var/www
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - app
    networks:
      - laravel
    ports:
      - "80:80"

networks:
  laravel:
    driver: bridge